# Keys found on w3resources.com
twitter:
  consumer_key: sqrzNfTYAhdKKFe8i0jkbmfJc
  consumer_secret: UY4UiIjYTuB4Z09Kh5ZeC8nA1M9rPT9VNNutZa8wPivVCj6SoV
  access_token: 217674868-6jGUXSmNd1ldEgPm19Ms0sOVd1NWHlqOPOvDjD1Z
  access_token_secret: KehU1HYSmeo5JrNhlWbPrqXPaVWJMr2gi72UINuaDAufQ
