name: flutter_feed
description: Flutter feed generator

dependencies:
  flutter:
    sdk: flutter
  twitter: 0.5.2

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true