name: flutter_feed
description: Flutter feed generator
author : Alexi Coard

dependencies:
  flutter:
    sdk: flutter
  twitter: 1.0.0
  url_launcher: ^3.0.0
  yaml: any
  http: ^0.11.3+16

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/retweet.svg
    - config.yaml